# Single source of truth for Transfermarkt -> Statz team name mapping.
# Used by projection_service.py and euro_comp_projection_service.py.
# Add new entries here when Sportmonks renames a team.

TEAM_MAPPING = {
    'Bournemouth': 'AFC Bournemouth',
    'Wimbledon': 'AFC Wimbledon',
    'Esporte Clube Juventude': 'Juventude',
    'Sport Club Corinthians Paulista': 'Corinthians',
    'Esporte Clube Bahia': 'Bahia',
    'Clube de Regatas Vasco da Gama': 'Vasco da Gama',
    'CR Flamengo': 'Flamengo',
    'Fluminense Football Club': 'Fluminense',
    'Sport Club do Recife': 'Sport Recife',
    'Sport Club Internacional': 'Internacional',
    'Botafogo de Futebol e Regatas': 'Botafogo',
    'Grêmio Foot-Ball Porto Alegrense': 'Grêmio',
    'Cruzeiro Esporte Clube': 'Cruzeiro',
    'Sociedade Esportiva Palmeiras': 'Palmeiras',
    'Clube Atlético Mineiro': 'Atlético Mineiro',
    'Esporte Clube Vitória': 'Vitória',
    'São Paulo Futebol Clube': 'São Paulo',
    'Fortaleza Esporte Clube': 'Fortaleza',
    'Santos': 'Santos',
    'Red Bull Bragantino': 'Bragantino',
    'Mirassol Futebol Clube (SP)': 'Mirassol',
    'Ceará Sporting Club': 'Ceará',
    'D.C. United': 'DC United',
    'Orlando City SC': 'Orlando City',
    'San Jose Earthquakes': 'SJ Earthquakes',
    'Sporting Kansas City': 'Sporting KC',
    'New York Red Bulls': 'New York RB',
    'Red Bull New York': 'New York RB',
    'Los Angeles Galaxy': 'LA Galaxy',
    'New England Revolution': 'New England',
    'Real Salt Lake City': 'Real Salt Lake',
    'Los Angeles': 'Los Angeles FC',
    'Inter Miami CF': 'Inter Miami',
    'St. Louis CITY': 'St. Louis City',
    'Nashville': 'Nashville SC',
    'Montréal': 'CF Montréal',
    'Barcelona': 'FC Barcelona',
    'Getafe CF': 'Getafe',
    'Villarreal CF': 'Villarreal',
    'Atlético de Madrid': 'Atlético Madrid',
    'Athletic Bilbao': 'Athletic Club',
    'Real Betis Balompié': 'Real Betis',
    'Valencia CF': 'Valencia',
    'Levante UD': 'Levante',
    'CA Osasuna': 'Osasuna',
    'Espanyol Barcelona': 'Espanyol',
    'RCD Mallorca': 'Mallorca',
    'Elche CF': 'Elche',
    'Paris Saint-Germain': 'Paris Saint Germain',
    'AS Monaco': 'Monaco',
    'OGC Nice': 'Nice',
    'Olympique Lyon': 'Olympique Lyonnais',
    'Stade Rennais': 'Rennes',
    'RC Lens': 'Lens',
    'Aston Villa ': 'Aston Villa FC',
    'RC Strasbourg Alsace': 'Strasbourg',
    'Stade Brestois 29': 'Brest',
    'AJ Auxerre': 'Auxerre',
    'Le Havre AC': 'Le Havre',
    'S Napoli': 'Napoli',
    'Inter Milan': 'Inter',
    'Milan': 'AC Milan',
    'Bologna  1909': 'Bologna',
    'A Fiorentina': 'Fiorentina',
    'Como 1907': 'Como',
    'Pisa Sporting Club': 'Pisa',
    'Cagliari Calcio': 'Cagliari',
    'Genoa C': 'Genoa',
    'Parma Calcio 1913': 'Parma',
    'Udinese Calcio': 'Udinese',
    'LO Lille': 'LOSC Lille',
    'Angers O': 'Angers SCO',
    'Bayern Munich': 'FC Bayern München',
    '1.FSV Mainz 05': 'FSV Mainz 05',
    'Freiburg': 'SC Freiburg',
    'SV Werder Bremen': 'Werder Bremen',
    '1. Union Berlin': 'FC Union Berlin',
    '1. Köln': 'FC Köln',
    'Augsburg': 'FC Augsburg',
    '1. Heidenheim 1846': 'Heidenheim',
    'TSG 1899 Hoffenheim': 'TSG Hoffenheim',
    'PSV Eindhoven': 'PSV',
    'Feyenoord Rotterdam': 'Feyenoord',
    'Ajax Amsterdam': 'Ajax',
    'AZ Alkmaar': 'AZ',
    'Utrecht': 'FC Utrecht',
    'Twente Enschede': 'FC Twente',
    'Heerenveen': 'SC Heerenveen',
    'Groningen': 'FC Groningen',
    'Excelsior Rotterdam': 'Excelsior',
    'N Breda': 'NAC Breda',
    'Volendam': 'FC Volendam',
    'Heart of Midlothian': 'Hearts',
    'SL Benfica': 'Benfica',
    'Braga': 'Sporting Braga',
    'CD Santa Clara': 'Santa Clara',
    'GD Estoril Praia': 'Estoril',
    'Vitória Guimarães': 'Vitória SC',
    'CD Tondela': 'Tondela',
    'CD Nacional': 'Nacional',
    'Avs Futebol': 'AVS',
    'Club Athletico Paranaense': 'Athletico PR',
    'Clube do Remo (PA)': 'Remo',
    'Coritiba Foot Ball Club': 'Coritiba',
    'Associação Chapecoense de Futebol': 'Chapecoense',
}
